### ISSUE TITLE
Loader fails when circular dependencies exist within an application

### ISSUE THREAD

**Issue by bizob2828** [DataDog/import-in-the-middle#32]
## Expected Behavior
When running an application that has circular deps with `import-in-the-middle`, it should handle this accordingly.

## Actual Behavior
It silent fails in pre Node 20, and in Node 20 errors with

```sh
file:///Users/revans/code/cyclic-loader-issue/dep-2.js:5
  dep1()
  ^

ReferenceError: Cannot access 'dep1' before initialization
    at dep2 (file:///Users/revans/code/cyclic-loader-issue/dep-2.js:5:3)
    at file:///Users/revans/code/cyclic-loader-issue/dep-1.js:7:1
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:308:24)
    at async loadESM (node:internal/process/esm_loader:42:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)
```

## Steps to Reproduce the Problem

  1. `git clone https://github.com/bizob2828/cyclic-loader-issue`
  1. `npm i && npm run start`

## Specifications

  - Version: Node 16,18,20. 
  - Platform: All
  - Subsystem: All

**Comment by timfish** [comment]
Confirmed this is still an issue with v1.8.1

**Comment by jsumners-nr** [comment]
> Hi - is there any chance on solving this?

Pull requests are welcome.

**Comment by BridgeAR** [comment]
This is similar to the langchain report and very difficult to fix.

It would require a retry mechanism and that would not be deterministic, if I am not mistaken.

Refs https://github.com/nodejs/import-in-the-middle/issues/227
