### ISSUE TITLE
Does not handle CallExpression in ExportDefaultDeclaration node

### ISSUE THREAD

**Issue by mohd-akram** [DataDog/import-in-the-middle#77]
## Expected Behavior
Works.

## Actual Behavior

```javascript
TypeError: Cannot read properties of undefined (reading 'name')
    at getEsmExports (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/lib/get-esm-exports.js:71:59)
    at getExports (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/lib/get-exports.js:80:12)
    at async processModule (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/hook.js:134:23)
    at async processModule (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/hook.js:160:20)
    at async processModule (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/hook.js:160:20)
    at async processModule (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/hook.js:160:20)
    at async processModule (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/hook.js:160:20)
    at async processModule (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/hook.js:160:20)
    at async getSource (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/hook.js:269:60)
    at async load (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/hook.js:335:26)
```

## Steps to Reproduce the Problem

I'm getting this after updating Sentry to 8.x. I'm not sure where exactly `import-in-the-middle` is being called from, but the gist of it is that it is crashing on [this file](https://github.com/SoftwareBrothers/adminjs/blob/master/src/frontend/components/app/sort-link.tsx) (`node_modules/adminjs/lib/frontend/components/app/sort-link.js`) because it has a function call in the export.

  1. `require('import-in-the-middle/lib/get-esm-exports')({moduleSource: 'export default parseInt("1");', defaultAs: 'sortLink'})`

## Specifications

  - Version: 1.7.4
  - Platform: macOS
  - Subsystem: ?

**Comment by timfish** [comment]
I haven't seen one before!

Can you try applying [this patch](https://github.com/getsentry/sentry-javascript/issues/12242#issuecomment-2133993135) which combines a load of outstanding PRs?

**Comment by mohd-akram** [comment]
Tried it, it doesn't work. It only patches `hook.js` while the problem is in `get-esm-exports.js`.

**Comment by timfish** [comment]
I've tried reproducing this with a simple `export default parseInt("1")` but it parses without error. Do you have a more full example to reproduce this?

**Comment by mohd-akram** [comment]
The issue only happens when `defaultAs` is provided, as in the one-liner I mentioned. I imagine it comes from [here](https://github.com/SoftwareBrothers/adminjs/blob/e27e885e819529b0dd9ba2e5b64e6afade1b59aa/src/frontend/components/app/index.ts#L18) in the library where this happens. The code expects a function node but doesn't check the type: https://github.com/DataDog/import-in-the-middle/blob/bf3a4fbb0b0a4fd806aefb8d2a598894303a0ebf/lib/get-esm-exports.js#L67-L70
